name: "VPS Deploy"
on:
    push:
        branches:
            - main
jobs:
    build_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4
            - name: "Deploy to VPS"
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                passphrase: ${{ secrets.PASSPHRASE}}
                port: ${{ secrets.PORT }}
                source: "."
                target: ${{ secrets.TARGET }}