name: TheHatchButton.com CI
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubunto-latest
        steps:
            - name: Repository Checkout
              uses: actions/checkout@1
            - name: Deploy
              uses: easingthemes/ssh-deploy@main
              env: 
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rltgoDzvO --delete"
                SOURCE: "public/"
                REMOTE_HOST: ${{secrets.REMOTE_HOST}}
                REMOTE_USER: ${{secrets.REMOTE_USER}}
                REMOTE_PORT: ${{secrets.REMOTE_PORT}}
                TARGET: ${{secrets.REMOTE_TARGET}}